### ISSUE TITLE
Missing Releases Folder 

### ISSUE THREAD

**Issue by narner** [fiebrink1/WekiInputHelper#1]
Hi Rebecca, 

I ended up finding the [installer on the Wekinator website](http://www.wekinator.org/kadenze/#Install_the_8220WekiInputHelper8221), but thought I'd let you know that it looks as if the .zip download from the repository seems to be missing the Releases folder: 

![screen shot 2016-04-09 at 8 52 54 am](https://cloud.githubusercontent.com/assets/2131591/14403752/410c2170-fe31-11e5-8aa2-24c53f57564e.png)

Hope this is helpful!

**Comment by fiebrink1** [comment]
I'm not sure I understand your question -- are you saying that clicking "download zip" directly in github doesn't give you any binaries along with the source code? If so, that's the desired behavior -- the installers are really big files and not under version control. You can go to https://github.com/fiebrink1/wekimini/releases to select just the one for your OS, or to grab a .zip of the source code for that release tag.

Or am I misunderstanding your question?

**Comment by narner** [comment]
@fiebrink1 This was my mistake; I think I had misread the installation instructions. My apologies, Rebecca!
